### ISSUE TITLE
typing package should not be installed in python 3.5+

### ISSUE THREAD

**Issue by kmantel** [LEMS/pylems#61]
According to https://pypi.org/project/typing/#description:

> For package maintainers, it is preferred to use typing;python_version<"3.5" if your package requires it to support earlier Python versions. This will avoid shadowing the stdlib typing module when your package is installed via pip install -t . on Python 3.5 or later.

Introduced in 64bf0a7043c3e1597b199b25c2a93c8f41ec8be5, the typing package shadows the python native typing package present in 3.5+ and can result in `AttributeError: type object 'Callable' has no attribute '_abc_registry'` errors when installing certain dependency combinations. See https://github.com/python/typing/issues/573

**Comment by sanjayankur31** [comment]
Fixed in development now, thanks.
